"""initial migration

Revision ID: d8efc58c3ece
Revises: 
Create Date: 2026-05-23 23:07:12.905511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8efc58c3ece'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('nome_marca', sa.String(length=255), nullable=False),
    sa.Column('icone', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_nome_marca'), 'marcas', ['nome_marca'], unique=False)
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('modelos',
    sa.Column('marca_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor_fipe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('icone', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_marca_id'), 'modelos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_modelos_nome'), 'modelos', ['nome'], unique=False)
    op.create_table('carros',
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.Enum('FLEX', 'GASOLINA', 'DIESEL', 'ELETRICO', 'HIBRIDO', name='combustivel_enum'), nullable=False),
    sa.Column('num_portas', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=100), nullable=False),
    sa.Column('quilometragem', sa.Integer(), nullable=False),
    sa.Column('valor_anuncio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carros_modelo_id'), 'carros', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_carros_usuario_id'), 'carros', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carros_usuario_id'), table_name='carros')
    op.drop_index(op.f('ix_carros_modelo_id'), table_name='carros')
    op.drop_table('carros')
    op.drop_index(op.f('ix_modelos_nome'), table_name='modelos')
    op.drop_index(op.f('ix_modelos_marca_id'), table_name='modelos')
    op.drop_table('modelos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_marcas_nome_marca'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
